language: scala

# run on new infrastructure
sudo: false
cache:
  apt: true
  directories:
    $HOME/.ivy2
    target
    tests/install

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      - dc
      - python-numpy
      - python-matplotlib


# Directory structure:
#   /home/travis/build/bu-icsg
#            |--> riscv/
#            |--> rocket-chip/
#            |--> xfiles-dana/

env:
  global:
    - ROCKETCHIP=$TRAVIS_BUILD_DIR/../rocket-chip
    - XFILES=$TRAVIS_BUILD_DIR
    - ROCKETCHIP_ADDONS=xfiles-dana
    - PATH=$PATH:$XFILES/usr/bin
  matrix:
    - PES=1 EPB=4
    - PES=4 EPB=4
    - PES=8 EPB=8
    - PES=8 EPB=16

before_install:
  - export CXX=g++-4.8 CC=gcc-4.8
  - export CPP_CONFIG=XFilesDanaCppPe$PES\Epb$EPB\Config
  - travis-before-install

script:
  - cd $XFILES/tests
  - ./regress.sh

before_cache:
  # Remove all but the most recent installs from getting cached
  - ls -tr tests/install | tail -n+2 | sed s@^@regression/install/@ | xargs rm -rf
